openapi: 3.1.0
info:
  title: CMS Training Project API
  version: 1.0.0
  description: |
    A simple API for storing, searching and retrieving articles
servers:
  - url: https://localhost:3000
    description: Local development environment

components:
  schemas:
  # Schema for author details
    Author:
      type: object
      required: [firstName, lastName, email]
      properties:
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
          format: email
        id:
          type: string
          readOnly: true
          format: uuid

  # Schema for an article
    Article:
      type: object
      required: [headline, content, author]
      properties:
        id:
          type: string
          readOnly: true
          format: uuid
        headline:
          type: string
        content:
          type: string
        author:
           $ref: '#/components/schemas/Author'

  # Schema for creating an article with existing author details 
    ArticleWithExistingAuthor:
      type: object
      required: [headline, content, authorId]
      properties:
        id:
          type: string
          readOnly: true
          format: uuid
        headline:
          type: string
        content:
          type: string
        authorId:
          type: string
          format: uuid

  # Schema for relevance based search of an author
    AuthorSearchResult:
      type: object
      properties:
        totalSearchResults:
          type: integer
          example: 10
        results:
          type: array
          items:
            type: object
            properties:
              author:
                $ref: '#/components/schemas/Author'

    # Schema for relevance based search of an article
    ArticleSearchResult:
      type: object
      properties:
        totalSearchResults:
          type: integer
          example: 10
        results:
          type: array
          items:
            type: object
            properties:
              article:
                $ref: '#/components/schemas/Article'

paths:

# PATHS RELATED TO AUTHORS

  /authors:
  # 1. GET list of all authors and their details 
    get:
      summary: Get all authors
      operationId: getAuthors # operationId - a unique identifier for the operation, which can be used for code generation and client libraries.
      tags: #tags - group and organize API endpoints for documentation and Swagger UI
      - Authors 
      responses:
        '200':
          description: A list of all authors
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Author'

  # 2. Create a new author
    post:
      summary: Create a new author
      operationId: createAuthor
      tags:
      - Authors
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Author'
      responses:
        '201':
          description: Author created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Author'

        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Invalid input

        '409':                                  
          description: Author already exists
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Author already exists

  /authors/search:
  # 3. Search for authors based on query
    get:
        summary: Search for authors by query
        operationId: searchAuthors
        tags: 
        - Authors
        parameters:
          - name: q
            in: query
            required: true
            schema:
              type: string
            description: |
              Search query can be firstName, lastName or email of the author
        responses:
          '200':
            description: |
              Author matching the search query is found
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/AuthorSearchResult'

          '400':
            description: Invalid search query
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    message:
                      type: string
                      example: Invalid search query

  /authors/{id}:
  # 4. GET author details by Id
    get:
      summary: Get author details by ID
      operationId: getAuthorById
      tags:
      - Authors
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Author retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  author:
                    $ref: '#/components/schemas/Author'

        '404':
          description: Author not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Author not found

  # 5. Update an existing author's details
    put:
      summary: Update an existing author's details 
      operationId: updateAuthorById
      tags: 
      - Authors
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Author'
      responses:
        '200':
          description: Author updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Author'

        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Invalid input

        '404':
          description: Author not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: No author found
        
        '409':                                  
          description: Author already exists
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Author already exists

  # 6. Delete an existing author 
    delete:
      summary: Delete an existing author and articles remaining unaffected
      operationId: deleteAuthorById
      tags:
      - Authors
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Author deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Author details deleted successfully and articles remain unaffected

        '404':
          description: Author not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Author not found

# PATHS RELATED TO ARTICLES

  /articles:
  # 1. GET list of all articles and their details 
    get:
      summary: Get all articles
      operationId: getArticles
      tags: 
      - Articles
      responses:
        '200':
          description: A list of all articles
          content:
            application/json:
              schema:
                type: array
                items:
                   $ref: '#/components/schemas/Article'
        '404':
          description: No articles found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: No articles found

  # 2. Create a new article
    post:
      summary: Create a new article 
      operationId: createArticle
      tags:
      - Articles
      requestBody:
        required: true
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/Article' 
                - $ref: '#/components/schemas/ArticleWithExistingAuthor'

      responses:
        '201':
          description: Article created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Article'

        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Invalid input
        '409':
          description: Article already exists
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Article already exists

  /articles/search:
  # 3. Search for articles by keyword
    get:
      summary: Search for articles by keyword
      operationId: searchArticles
      tags:
      - Articles
      parameters:
          - name: q
            in: query
            required: true
            schema:
              type: string
            description: |
              Search keyword can be any from an article headline or content.
      responses:
        '200': 
          description: |
            Article(s) matching the search keyword are listed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArticleSearchResult'

        '404':
            description: No articles found 
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    message:
                      type: string
                      example: No articles found

  /articles/author/{id}:
  # 4. Get articles for a specific Author ID
    get:
      summary: Get list of articles written by an author
      operationId: getArticlesByAuthorId
      tags:
      - Articles
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: List of articles written by the author retrieved successfully 
          content:
            application/json:
              schema:
                type: object
                properties:
                  author:
                    $ref: '#/components/schemas/Author'
                  articles:
                    type: array
                    items:
                      allOf:
                        - $ref: '#/components/schemas/Article'
                        - properties:
                            author:
                              readOnly: true

        '404':
          description: Author not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Author not found


  /articles/{id}:
  # 5. GET article by Id
    get:
      summary: Get article by ID
      operationId: getArticleById
      tags:
      - Articles
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Article retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  author:
                    $ref: '#/components/schemas/Article'

        '404':
          description: Article not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Article not found


  # 6. Update an existing article details
    put:
      summary: Update an existing article details
      operationId: updateArticleById
      tags:
      - Articles
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                headline:
                  type: string
                content:
                  type: string
      responses:
        '200':
          description: Article updated successfully (author remains unchanged)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Article'

        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Invalid input

        '404':
          description: Article not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Article not foun

    # 7. Delete an article - author remains unchanged
    delete:
      summary: Delete an article (author remains unchanged)
      operationId: deleteArticleById
      tags:
        - Articles
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Article deleted successfully - author remains unchanged
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Article deleted successfully
        '404':
          description: Article not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Article not found

  
 



            






